name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.8
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^3.0.0
